
package View;

import Control.CCustomer;
import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import javax.swing.JTable;
import javax.swing.JTextField;

public class Customer extends javax.swing.JFrame {

public static Customer Instance;
public JTable t11;
public JTextField id;
public JTextField name;
public JTextField address;
public JTextField phone_no;
public JTextField search;
public JLabel iid;
public JLabel nname;
public JLabel aad;
public JLabel pphone;


      
    public Customer() {
        initComponents();
        Instance=this;
        t11=tblCustomer;
        id=txt_cus_id1;
        name=txt_cus_name1;
        address=txt_address;
        phone_no=txt_phone_no;
        search=txt_search;
        iid=err_id;
        nname=err_name;
        aad=err_add;
        pphone=err_no;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_address = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_cus_id1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_cus_name1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_phone_no = new javax.swing.JTextField();
        btn_edit = new javax.swing.JButton();
        btn_delete2 = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCustomer = new javax.swing.JTable();
        btn_save1 = new javax.swing.JButton();
        txt_search = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        err_id = new javax.swing.JLabel();
        err_name = new javax.swing.JLabel();
        err_add = new javax.swing.JLabel();
        err_no = new javax.swing.JLabel();
        err_id1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("<<Back");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 539, 68, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 600));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 860, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Address");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        txt_address.setBackground(new java.awt.Color(255, 255, 255));
        txt_address.setForeground(new java.awt.Color(0, 0, 0));
        txt_address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_addressKeyReleased(evt);
            }
        });
        jPanel1.add(txt_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 198, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Customer ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        txt_cus_id1.setBackground(new java.awt.Color(255, 255, 255));
        txt_cus_id1.setForeground(new java.awt.Color(0, 0, 0));
        txt_cus_id1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cus_id1KeyReleased(evt);
            }
        });
        jPanel1.add(txt_cus_id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 198, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Customer Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        txt_cus_name1.setBackground(new java.awt.Color(255, 255, 255));
        txt_cus_name1.setForeground(new java.awt.Color(0, 0, 0));
        txt_cus_name1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cus_name1KeyReleased(evt);
            }
        });
        jPanel1.add(txt_cus_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 198, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Phone No");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));

        txt_phone_no.setBackground(new java.awt.Color(255, 255, 255));
        txt_phone_no.setForeground(new java.awt.Color(0, 0, 0));
        txt_phone_no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_phone_noKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_phone_noKeyTyped(evt);
            }
        });
        jPanel1.add(txt_phone_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 198, -1));

        btn_edit.setBackground(new java.awt.Color(255, 255, 255));
        btn_edit.setForeground(new java.awt.Color(0, 153, 204));
        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        jPanel1.add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 80, 40));

        btn_delete2.setBackground(new java.awt.Color(255, 255, 255));
        btn_delete2.setForeground(new java.awt.Color(0, 153, 204));
        btn_delete2.setText("Delete");
        btn_delete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_delete2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 80, 40));

        btn_clear.setBackground(new java.awt.Color(255, 255, 255));
        btn_clear.setForeground(new java.awt.Color(0, 153, 204));
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        jPanel1.add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, 80, 40));

        tblCustomer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CustomerId", "CustomerName", "Address", "Phone "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCustomer.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblCustomerAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tblCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCustomerMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCustomer);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 510, 250));

        btn_save1.setBackground(new java.awt.Color(255, 255, 255));
        btn_save1.setForeground(new java.awt.Color(0, 153, 204));
        btn_save1.setText("Save");
        btn_save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_save1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_save1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 80, 40));

        txt_search.setBackground(new java.awt.Color(255, 255, 255));
        txt_search.setForeground(new java.awt.Color(0, 0, 0));
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        jPanel1.add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 198, -1));

        btn_search.setForeground(new java.awt.Color(0, 153, 204));
        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });
        jPanel1.add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 80, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Customer List");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, -1));
        jPanel1.add(err_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 200, 20));
        jPanel1.add(err_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 200, 20));
        jPanel1.add(err_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 200, 20));
        jPanel1.add(err_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 200, 20));
        jPanel1.add(err_id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 200, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1000, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
      
    }//GEN-LAST:event_formMouseClicked

    private void btn_save1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_save1ActionPerformed
   
    if(txt_cus_id1.getText().trim().isEmpty())
    {
    err_id.setText("Id cannot be empty");
    err_id.setForeground(Color.red);
    }
    if(txt_cus_name1.getText().trim().isEmpty())
    {
    err_name.setText("Name cannot be empty");
    err_name.setForeground(Color.red);
    }
    if(txt_address.getText().trim().isEmpty())
    {
    err_add.setText("Address cannot be empty");
    err_add.setForeground(Color.red);
    }
    if(txt_phone_no.getText().trim().isEmpty())
    {
    err_no.setText("Phone no cannot be empty");
    err_no.setForeground(Color.red);
    }
    else
    {
        String id,name,address;
        id=txt_cus_id1.getText();
        name=txt_cus_name1.getText();
        address=txt_address.getText();
        int no1=Integer.parseInt(txt_phone_no.getText());
        CCustomer x=new CCustomer();
        x.letssave(id,name,address,no1);
    }
    
   
    }//GEN-LAST:event_btn_save1ActionPerformed

    private void tblCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCustomerMouseClicked
        err_id.setText("");
        err_name.setText("");
        err_add.setText("");
        err_no.setText("");
        err_id1.setText("");
        CCustomer a=new CCustomer();
        a.bringData1();
    }//GEN-LAST:event_tblCustomerMouseClicked

    private void tblCustomerAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblCustomerAncestorAdded
       CCustomer y=new CCustomer();
        y.Display1();
    }//GEN-LAST:event_tblCustomerAncestorAdded

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        CCustomer o=new CCustomer();
        o.Reset1();
        err_id.setText("");
        err_name.setText("");
        err_add.setText("");
        err_no.setText("");
        err_id1.setText("");
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_delete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete2ActionPerformed
   if(txt_cus_id1.getText().trim().isEmpty())
    {
    err_id.setText("Id cannot be empty");
    err_id.setForeground(Color.red);
    }
    if(txt_cus_name1.getText().trim().isEmpty())
    {
    err_name.setText("Name cannot be empty");
    err_name.setForeground(Color.red);
    }
    if(txt_address.getText().trim().isEmpty())
    {
    err_add.setText("Address cannot be empty");
    err_add.setForeground(Color.red);
    }
    if(txt_phone_no.getText().trim().isEmpty())
    {
    err_no.setText("Phone no cannot be empty");
    err_no.setForeground(Color.red);
    }
    else
    {
        String h=txt_cus_id1.getText();
        CCustomer p=new CCustomer();
        p.deleteData1(h);
    }
    }//GEN-LAST:event_btn_delete2ActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
    if(txt_cus_id1.getText().trim().isEmpty())
    {
    err_id.setText("Id cannot be empty");
    err_id.setForeground(Color.red);
    }
    if(txt_cus_name1.getText().trim().isEmpty())
    {
    err_name.setText("Name cannot be empty");
    err_name.setForeground(Color.red);
    }
    if(txt_address.getText().trim().isEmpty())
    {
    err_add.setText("Address cannot be empty");
    err_add.setForeground(Color.red);
    }
    if(txt_phone_no.getText().trim().isEmpty())
    {
    err_no.setText("Phone no cannot be empty");
    err_no.setForeground(Color.red);
    }
    else
    {
        String id,name,address;
        id=txt_cus_id1.getText();
        name=txt_cus_name1.getText();
        address=txt_address.getText();
        int phone=Integer.parseInt(txt_phone_no.getText());

        CCustomer x=new CCustomer();
        x.editData1(id,name,address,phone);
    }
    }//GEN-LAST:event_btn_editActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked

        this.toBack();
        setVisible(false);
        DashBoard b=new DashBoard();
        b.setVisible(true);
        b.toFront();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
    err_id.setText("");
    err_name.setText("");
    err_add.setText("");
    err_no.setText("");
    err_id1.setText("");
    if(txt_search.getText().trim().isEmpty())
    {
    err_id1.setText("Id cannot be empty");
    err_id1.setForeground(Color.red);
    }
   else{
        String id=txt_search.getText();
        CCustomer l=new  CCustomer();
        l.search(id);
        }
    }//GEN-LAST:event_btn_searchActionPerformed

    private void txt_cus_id1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cus_id1KeyReleased
         err_id.setText("");
    }//GEN-LAST:event_txt_cus_id1KeyReleased

    private void txt_cus_name1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cus_name1KeyReleased
         err_name.setText("");
    }//GEN-LAST:event_txt_cus_name1KeyReleased

    private void txt_addressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_addressKeyReleased
        err_add.setText("");
    }//GEN-LAST:event_txt_addressKeyReleased

    private void txt_phone_noKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_phone_noKeyReleased
         err_no.setText("");
    }//GEN-LAST:event_txt_phone_noKeyReleased

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
      err_id1.setText("");
    }//GEN-LAST:event_txt_searchKeyReleased

    private void txt_phone_noKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_phone_noKeyTyped
       char c=evt.getKeyChar();
       if(Character.isLetter(c))
       {
           txt_phone_no.setEditable(false);
       }
       else
       {
           txt_phone_no.setEditable(true);
       }
    }//GEN-LAST:event_txt_phone_noKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete2;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_save1;
    private javax.swing.JButton btn_search;
    private javax.swing.JLabel err_add;
    private javax.swing.JLabel err_id;
    private javax.swing.JLabel err_id1;
    private javax.swing.JLabel err_name;
    private javax.swing.JLabel err_no;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblCustomer;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_cus_id1;
    private javax.swing.JTextField txt_cus_name1;
    private javax.swing.JTextField txt_phone_no;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
