/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import Control.CDeployContainers;
import static View.Customer.Instance;
import static View.DeployContainers.Instance;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.JXDatePicker;

/**
 *
 * @author DELL
 */
public class DeployContainers extends javax.swing.JFrame {

    public static  DeployContainers Instance;
    public JTable tb1;
    public JTable tb2;
    public JTextField id;
    public JTextField reg_no1;
    public JComboBox model;
    public JComboBox name;
    public JXDatePicker date;
    public JXDatePicker returndate;
    public JTextField price;
    public DeployContainers() {
        initComponents();
        Instance=this;
        tb1=container_tbl;
        tb2=deploy_tbl;
        id=txt_id;
        reg_no1=txt_registration;
        model=cmb_model;
        name=cmb_name;
        date=deploy_date;
        returndate=return_date;
        price=txt_price;
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        return_date = new org.jdesktop.swingx.JXDatePicker();
        jLabel15 = new javax.swing.JLabel();
        btn_deploy = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        deploy_tbl = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        deploy_date = new org.jdesktop.swingx.JXDatePicker();
        jLabel19 = new javax.swing.JLabel();
        cmb_model = new javax.swing.JComboBox<>();
        cmb_name = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txt_registration = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        container_tbl = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        err_id = new javax.swing.JLabel();
        err_regi = new javax.swing.JLabel();
        err_model = new javax.swing.JLabel();
        err_price = new javax.swing.JLabel();
        err_name = new javax.swing.JLabel();
        err_dp = new javax.swing.JLabel();
        err_ret = new javax.swing.JLabel();
        txt_price = new javax.swing.JTextField();
        btn_clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("<<Back");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(543, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 140, 620));

        txt_id.setBackground(new java.awt.Color(255, 255, 255));
        txt_id.setForeground(new java.awt.Color(0, 0, 0));
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });
        txt_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_idKeyReleased(evt);
            }
        });
        jPanel3.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 198, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Model");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Customer Name");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        return_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                return_dateActionPerformed(evt);
            }
        });
        jPanel3.add(return_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 200, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Price");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, -1, -1));

        btn_deploy.setBackground(new java.awt.Color(255, 255, 255));
        btn_deploy.setForeground(new java.awt.Color(0, 153, 204));
        btn_deploy.setText("Deploy");
        btn_deploy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deployActionPerformed(evt);
            }
        });
        jPanel3.add(btn_deploy, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 560, 80, 40));

        deploy_tbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deploy_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Deploy ID", "Registration No", "Model", "Customer Name", "Deploy Date", "Return Date", "Price"
            }
        ));
        deploy_tbl.setRowHeight(23);
        deploy_tbl.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                deploy_tblAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane3.setViewportView(deploy_tbl);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 610, 160));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Deploy Id");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Deploy Container List");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, -1, -1));

        deploy_date.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deploy_dateMouseClicked(evt);
            }
        });
        deploy_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deploy_dateActionPerformed(evt);
            }
        });
        jPanel3.add(deploy_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 200, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Deploy Date");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, -1, -1));

        cmb_model.setBackground(new java.awt.Color(255, 255, 255));
        cmb_model.setForeground(new java.awt.Color(0, 0, 0));
        cmb_model.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dry Storage Container", "Flat Rack Container", "Open top container", "Special purpose container " }));
        cmb_model.setSelectedIndex(-1);
        cmb_model.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_modelActionPerformed(evt);
            }
        });
        cmb_model.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cmb_modelKeyReleased(evt);
            }
        });
        jPanel3.add(cmb_model, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 198, -1));

        cmb_name.setBackground(new java.awt.Color(255, 255, 255));
        cmb_name.setForeground(new java.awt.Color(0, 0, 0));
        cmb_name.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cmb_nameAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        cmb_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_nameActionPerformed(evt);
            }
        });
        jPanel3.add(cmb_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 198, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Registration");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        txt_registration.setBackground(new java.awt.Color(255, 255, 255));
        txt_registration.setForeground(new java.awt.Color(0, 0, 0));
        txt_registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_registrationActionPerformed(evt);
            }
        });
        txt_registration.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_registrationKeyReleased(evt);
            }
        });
        jPanel3.add(txt_registration, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 198, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Return Date");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, -1, -1));

        container_tbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        container_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Regisration no", "Model", "Capacity", "Date of Purchase", "Status", "Price"
            }
        ));
        container_tbl.setRowHeight(23);
        container_tbl.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                container_tblAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        container_tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                container_tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(container_tbl);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 610, 200));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Available Container List");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, -1));
        jPanel3.add(err_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 200, 20));
        jPanel3.add(err_regi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 200, 20));
        jPanel3.add(err_model, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 190, 20));
        jPanel3.add(err_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, 200, 20));
        jPanel3.add(err_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 200, 20));
        jPanel3.add(err_dp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 200, 20));
        jPanel3.add(err_ret, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 200, 20));

        txt_price.setBackground(new java.awt.Color(255, 255, 255));
        txt_price.setForeground(new java.awt.Color(0, 0, 0));
        txt_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_priceActionPerformed(evt);
            }
        });
        txt_price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_priceKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_priceKeyTyped(evt);
            }
        });
        jPanel3.add(txt_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 198, -1));

        btn_clear.setForeground(new java.awt.Color(0, 153, 204));
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        jPanel3.add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 560, 70, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        this.toBack();
        setVisible(false);
        DashBoard b=new DashBoard();
        b.setVisible(true);
        b.toFront();
    }//GEN-LAST:event_jLabel18MouseClicked

    private void btn_deployActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deployActionPerformed
       if(txt_id.getText().trim().isEmpty())
       {
       err_id.setText("Id cannot be empty");
       err_id.setForeground(Color.red);
       }
       if(txt_registration.getText().trim().isEmpty())
       {
          err_regi.setText("Registration no cannot be empty");
          err_regi.setForeground(Color.red);
       }
       
       if(cmb_model.getSelectedIndex()==-1)
       {
           err_model.setText("Model no cannot be empty");
           err_model.setForeground(Color.red);
           
       }
       if(cmb_name.getSelectedIndex()==-1)
       {
           err_name.setText("Name cannot be empty");
           err_name.setForeground(Color.red);
       }
       if(deploy_date.getDate()==null)
       {
           err_dp.setText("Date cannot be empty");
           err_dp.setForeground(Color.red);
       }
       if(deploy_date.getDate()==null)
       {
           err_ret.setText("Return date cannot be empty");
           err_ret.setForeground(Color.red);
       }
       if(txt_price.getText().trim().isEmpty())
       {
           err_price.setText("Price cannot be empty");
           err_price.setForeground(Color.red);
       }
       
       else
       {
       String id,reg_no,model,name,date,return_d;
       int price;
       id=txt_id.getText();
       reg_no=txt_registration.getText();
       model=cmb_model.getSelectedItem().toString();
       name=cmb_name.getSelectedItem().toString();
       
       Date date1=deploy_date.getDate();
       DateFormat formate1=new SimpleDateFormat("yyy-MM-dd");
       date=formate1.format(date1);
       
       Date date2=return_date.getDate();
       DateFormat formate2=new SimpleDateFormat("yyy-MM-dd");
       return_d=formate1.format(date2);
       
       price=Integer.parseInt(txt_price.getText());
       
       CDeployContainers c=new CDeployContainers();
       c.deploy1(id,reg_no,model,name,date,return_d, price);
       }
    }//GEN-LAST:event_btn_deployActionPerformed

    private void container_tblAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_container_tblAncestorAdded
        CDeployContainers q=new CDeployContainers();
        q.DisplayContainers1();
    }//GEN-LAST:event_container_tblAncestorAdded

    private void container_tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_container_tblMouseClicked
        err_regi.setText("");
        err_model.setText("");
        err_name.setText("");
        err_price.setText("");
        CDeployContainers q=new CDeployContainers();
        q.bringData1();
        
      
    }//GEN-LAST:event_container_tblMouseClicked

    private void cmb_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_nameActionPerformed
        CDeployContainers w=new CDeployContainers();
        w.bringCustomer2();
    }//GEN-LAST:event_cmb_nameActionPerformed

    private void cmb_nameAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cmb_nameAncestorAdded
        CDeployContainers w=new CDeployContainers();
        w.bringCustomer2();
    }//GEN-LAST:event_cmb_nameAncestorAdded

    private void deploy_tblAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_deploy_tblAncestorAdded
       CDeployContainers k=new CDeployContainers();
       k.displayReturn1();
    }//GEN-LAST:event_deploy_tblAncestorAdded

    private void txt_registrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_registrationActionPerformed
      
    }//GEN-LAST:event_txt_registrationActionPerformed

    private void cmb_modelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_modelActionPerformed
       err_model.setText("");
    }//GEN-LAST:event_cmb_modelActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void txt_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_idKeyReleased
        err_id.setText("");
    }//GEN-LAST:event_txt_idKeyReleased

    private void txt_registrationKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_registrationKeyReleased
        err_regi.setText("");
    }//GEN-LAST:event_txt_registrationKeyReleased

    private void cmb_modelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmb_modelKeyReleased
    }//GEN-LAST:event_cmb_modelKeyReleased

    private void txt_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_priceActionPerformed

    private void txt_priceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_priceKeyReleased
        err_price.setText("");
    }//GEN-LAST:event_txt_priceKeyReleased

    private void deploy_dateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deploy_dateMouseClicked
       
    }//GEN-LAST:event_deploy_dateMouseClicked

    private void deploy_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deploy_dateActionPerformed
        err_dp.setText("");
    }//GEN-LAST:event_deploy_dateActionPerformed

    private void return_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_return_dateActionPerformed
       err_ret.setText("");
    }//GEN-LAST:event_return_dateActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        txt_id.setText("");
        txt_registration.setText("");
        cmb_model.setSelectedIndex(-1);
        cmb_name.setSelectedIndex(0);
        date.setDate(null);
        return_date.setDate(null);
        txt_price.setText("");
        err_regi.setText("");
        err_id.setText("");
        err_model.setText("");
        err_name.setText("");
        err_dp.setText("");
        err_ret.setText("");
        err_price.setText("");
    }//GEN-LAST:event_btn_clearActionPerformed

    private void txt_priceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_priceKeyTyped
        char c=evt.getKeyChar();
       if(Character.isLetter(c))
       {
           txt_price.setEditable(false);
       }
       else
       {
           txt_price.setEditable(true);
       }
    }//GEN-LAST:event_txt_priceKeyTyped


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeployContainers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeployContainers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeployContainers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeployContainers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeployContainers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_deploy;
    private javax.swing.JComboBox<String> cmb_model;
    private javax.swing.JComboBox<String> cmb_name;
    private javax.swing.JTable container_tbl;
    private org.jdesktop.swingx.JXDatePicker deploy_date;
    private javax.swing.JTable deploy_tbl;
    private javax.swing.JLabel err_dp;
    private javax.swing.JLabel err_id;
    private javax.swing.JLabel err_model;
    private javax.swing.JLabel err_name;
    private javax.swing.JLabel err_price;
    private javax.swing.JLabel err_regi;
    private javax.swing.JLabel err_ret;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private org.jdesktop.swingx.JXDatePicker return_date;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_price;
    private javax.swing.JTextField txt_registration;
    // End of variables declaration//GEN-END:variables
}
