/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import Control.CLoading;
import javax.swing.*;


/**
 *
 * @author DELL
 */
public class LoadingPage extends javax.swing.JFrame {

   public static LoadingPage Instance;
   public JLabel lbl;
   public JLabel lbl2;
   public JProgressBar pb;
    
    public LoadingPage() {
        initComponents();
        Instance=this;
        lbl=loadingtxt;
        lbl2=loading_value;
        pb=loadingbar;

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loadingtxt = new javax.swing.JLabel();
        loading_value = new javax.swing.JLabel();
        loadingbar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 255), new java.awt.Color(0, 153, 255), new java.awt.Color(0, 153, 255), new java.awt.Color(0, 153, 255)));
        jPanel1.setPreferredSize(new java.awt.Dimension(1139, 830));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loadingtxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        loadingtxt.setForeground(new java.awt.Color(0, 0, 0));
        loadingtxt.setText("Loading....");
        jPanel1.add(loadingtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, -1, -1));

        loading_value.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        loading_value.setForeground(new java.awt.Color(0, 0, 0));
        loading_value.setText("0 %");
        jPanel1.add(loading_value, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 540, -1, -1));

        loadingbar.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(loadingbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 1078, 18));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\OneDrive\\Pictures\\EAD Project\\newHit.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 560, 200));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1084, 694));

        setSize(new java.awt.Dimension(1000, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
     
      

    public static void main(String args[]) 
    {
        CLoading cd=new CLoading();
        cd.loadingPage();
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loading_value;
    private javax.swing.JProgressBar loadingbar;
    private javax.swing.JLabel loadingtxt;
    // End of variables declaration//GEN-END:variables

    public void setVisible(boolean b, boolean b0) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
