/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import Control.CCustomer;
import Control.CManageContainers;
import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import org.jdesktop.swingx.JXDatePicker;



public class ManageContainers extends javax.swing.JFrame {

   public static ManageContainers Instance;
   public JTable tb2;
   public JTextField reg_no;
   public JComboBox model;
   public JTextField capacity;
   public JXDatePicker date;
   public JTextField qty;
   public JComboBox status;
   public JTextField price;
   public JTextField search;
   public JLabel e;
    public ManageContainers() {
        initComponents();
        Instance=this;
        tb2=container_tbl;
        reg_no=txt_registration;
        model=cmb_model;
        capacity =txt_capacity;
        date=dob_purchase;
         
        status=cmb_status;
        price=txt_price;  
        search=txt_search;
        e=err_no;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_capacity = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmb_model = new javax.swing.JComboBox<>();
        cmb_status = new javax.swing.JComboBox<>();
        txt_price = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btn_clear = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        container_tbl = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        dob_purchase = new org.jdesktop.swingx.JXDatePicker();
        jLabel8 = new javax.swing.JLabel();
        txt_registration = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        err_no = new javax.swing.JLabel();
        err_cap = new javax.swing.JLabel();
        err_date = new javax.swing.JLabel();
        err_status = new javax.swing.JLabel();
        err_price = new javax.swing.JLabel();
        err_list = new javax.swing.JLabel();
        err_model = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("<<Back");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 539, 68, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 600));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 860, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Model");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Container List");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, -1));

        txt_capacity.setBackground(new java.awt.Color(255, 255, 255));
        txt_capacity.setForeground(new java.awt.Color(153, 153, 153));
        txt_capacity.setText("In cubic feets");
        txt_capacity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_capacityFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_capacityFocusLost(evt);
            }
        });
        txt_capacity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_capacityActionPerformed(evt);
            }
        });
        txt_capacity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_capacityKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_capacityKeyTyped(evt);
            }
        });
        jPanel1.add(txt_capacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 198, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Purhcase Date");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        cmb_model.setBackground(new java.awt.Color(255, 255, 255));
        cmb_model.setForeground(new java.awt.Color(0, 0, 0));
        cmb_model.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dry Storage Container", "Flat Rack Container", "Open top container", "Special purpose container " }));
        cmb_model.setSelectedIndex(-1);
        cmb_model.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_modelActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_model, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 198, -1));

        cmb_status.setBackground(new java.awt.Color(255, 255, 255));
        cmb_status.setForeground(new java.awt.Color(0, 0, 0));
        cmb_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sent", "Avaliable" }));
        cmb_status.setSelectedIndex(-1);
        cmb_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_statusActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 198, -1));

        txt_price.setBackground(new java.awt.Color(255, 255, 255));
        txt_price.setForeground(new java.awt.Color(0, 0, 0));
        txt_price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_priceKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_priceKeyTyped(evt);
            }
        });
        jPanel1.add(txt_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 198, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Price");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, -1, -1));

        btn_clear.setBackground(new java.awt.Color(255, 255, 255));
        btn_clear.setForeground(new java.awt.Color(0, 153, 204));
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        jPanel1.add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 530, 80, 40));

        btn_save.setBackground(new java.awt.Color(255, 255, 255));
        btn_save.setForeground(new java.awt.Color(0, 153, 204));
        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        jPanel1.add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 530, 80, 40));

        btn_edit.setBackground(new java.awt.Color(255, 255, 255));
        btn_edit.setForeground(new java.awt.Color(0, 153, 204));
        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        jPanel1.add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, 80, 40));

        btn_delete.setBackground(new java.awt.Color(255, 255, 255));
        btn_delete.setForeground(new java.awt.Color(0, 153, 204));
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 530, 80, 40));

        container_tbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        container_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Regisration no", "Model", "Capacity", "Date of Purchase", "Status", "Price"
            }
        ));
        container_tbl.setRowHeight(23);
        container_tbl.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                container_tblAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        container_tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                container_tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(container_tbl);
        if (container_tbl.getColumnModel().getColumnCount() > 0) {
            container_tbl.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 630, 250));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Capacity");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        dob_purchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dob_purchaseActionPerformed(evt);
            }
        });
        jPanel1.add(dob_purchase, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 200, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Status");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, -1, -1));

        txt_registration.setBackground(new java.awt.Color(255, 255, 255));
        txt_registration.setForeground(new java.awt.Color(0, 0, 0));
        txt_registration.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_registrationKeyReleased(evt);
            }
        });
        jPanel1.add(txt_registration, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 198, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Registration no");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        txt_search.setBackground(new java.awt.Color(255, 255, 255));
        txt_search.setForeground(new java.awt.Color(0, 0, 0));
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        jPanel1.add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 198, -1));

        btn_search.setForeground(new java.awt.Color(0, 153, 204));
        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });
        jPanel1.add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, -1, -1));
        jPanel1.add(err_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 200, 20));
        jPanel1.add(err_cap, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 190, 20));
        jPanel1.add(err_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 356, 200, 20));
        jPanel1.add(err_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 200, 20));
        jPanel1.add(err_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 200, 20));
        jPanel1.add(err_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 200, 20));
        jPanel1.add(err_model, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 190, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1000, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
       if(txt_registration.getText().trim().isEmpty())
       {
       err_no.setText("Id cannot be empty");
       err_no.setForeground(Color.red);
       }
       if(cmb_model.getSelectedIndex()==-1)
       {
           err_model.setText("Model no cannot be empty");
           err_model.setForeground(Color.red);
           
       }
       if(txt_capacity.getText().trim().isEmpty())
       {
           err_cap.setText("Capacity cannot be empty");
           err_cap.setForeground(Color.red);
           
       }
       if(dob_purchase.getDate()==null)
       {
           err_date.setText("Date cannot be empty");
           err_date.setForeground(Color.red);
       }
       if(cmb_status.getSelectedIndex()==-1)
       {
           err_status.setText("Status no cannot be empty");
           err_status.setForeground(Color.red);
           
       }
        if(txt_price.getText().trim().isEmpty())
       {
           err_price.setText("Price cannot be empty");
           err_price.setForeground(Color.red);
       }
       else
       {
        String register_no,model,date,status;

       register_no=txt_registration.getText();
       model=cmb_model.getSelectedItem().toString();
       int capacity=Integer.parseInt(txt_capacity.getText());
       Date date1=dob_purchase.getDate();
       DateFormat formate1=new SimpleDateFormat("yyy-MM-dd");
       date=formate1.format(date1);
      
       status=cmb_status.getSelectedItem().toString();
       int price=Integer.parseInt(txt_price.getText());

        CManageContainers q=new CManageContainers();
        q.save(register_no, model,capacity, date, status, price);
       }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
       this.toBack();
       setVisible(false);
       DashBoard b=new DashBoard();
       b.setVisible(true);
       b.toFront();
    }//GEN-LAST:event_jPanel2MouseClicked

    private void container_tblAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_container_tblAncestorAdded
        CManageContainers q=new CManageContainers();
        q.display1();
    }//GEN-LAST:event_container_tblAncestorAdded

    private void container_tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_container_tblMouseClicked
      err_no.setText("");
      err_cap.setText("");
      err_cap.setText("");
      err_date.setText("");
      err_status.setText("");
      err_price.setText("");
      err_list.setText("");
      CManageContainers b=new CManageContainers();
      b.bringData1();
       
    }//GEN-LAST:event_container_tblMouseClicked

    private void txt_capacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_capacityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_capacityActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
      err_no.setText("");
      err_cap.setText("");
      err_cap.setText("");
      err_date.setText("");
      err_status.setText("");
      err_price.setText("");
      err_list.setText("");
      CManageContainers b=new CManageContainers();
      b.reset1();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        if(txt_registration.getText().trim().isEmpty())
       {
       err_no.setText("Id cannot be empty");
       err_no.setForeground(Color.red);
       }
       if(cmb_model.getSelectedIndex()==-1)
       {
           err_model.setText("Model no cannot be empty");
           err_model.setForeground(Color.red);
           
       }
        if(txt_capacity.getText().trim().isEmpty())
       {
           err_cap.setText("Capacity cannot be empty");
           err_cap.setForeground(Color.red);
           
       }
       if(dob_purchase.getDate()==null)
       {
           err_date.setText("Date cannot be empty");
           err_date.setForeground(Color.red);
       }
       if(cmb_status.getSelectedIndex()==-1)
       {
           err_status.setText("Status no cannot be empty");
           err_status.setForeground(Color.red);
           
       }
        if(txt_price.getText().trim().isEmpty())
       {
           err_price.setText("Price cannot be empty");
           err_price.setForeground(Color.red);
       }
       else
       {
        String register_no,model,date,status;

       register_no=txt_registration.getText();
       model=cmb_model.getSelectedItem().toString();
       int capacity=Integer.parseInt(txt_capacity.getText());
       Date date1=dob_purchase.getDate();
       DateFormat formate1=new SimpleDateFormat("yyy-MM-dd");
       date=formate1.format(date1);
       status=cmb_status.getSelectedItem().toString();
       int price=Integer.parseInt(txt_price.getText());
       
        CManageContainers u=new CManageContainers();
        u.edit1(register_no, model,capacity, date, status, price);
       }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
       if(txt_registration.getText().trim().isEmpty())
       {
       err_no.setText("Id cannot be empty");
       err_no.setForeground(Color.red);
       }
       if(cmb_model.getSelectedIndex()==-1)
       {
           err_model.setText("Model no cannot be empty");
           err_model.setForeground(Color.red);
           
       }
        if(txt_capacity.getText().trim().isEmpty())
       {
           err_cap.setText("Capacity cannot be empty");
           err_cap.setForeground(Color.red);
           
       }
       if(dob_purchase.getDate()==null)
       {
           err_date.setText("Date cannot be empty");
           err_date.setForeground(Color.red);
       }
       if(cmb_status.getSelectedIndex()==-1)
       {
           err_status.setText("Status no cannot be empty");
           err_status.setForeground(Color.red);
           
       }
        if(txt_price.getText().trim().isEmpty())
       {
           err_price.setText("Price cannot be empty");
           err_price.setForeground(Color.red);
       }
       else
       {
       String re=txt_registration.getText();
       CManageContainers u=new CManageContainers();
       u.delete1(re);
       }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        this.toBack();
        setVisible(false);
        DashBoard b=new DashBoard();
        b.setVisible(true);
        b.toFront();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        err_no.setText("");
        err_model.setText("");
        err_cap.setText("");
        err_date.setText("");
        err_status.setText("");
        err_price.setText("");
        err_list.setText("");
        if(txt_search.getText().trim().isEmpty())
        {
           err_list.setText("List cannot be empty");
           err_list.setForeground(Color.red);
        }
        else
        {
        String id=txt_search.getText();
        CManageContainers l=new  CManageContainers();
        l.search(id);
        }
    }//GEN-LAST:event_btn_searchActionPerformed

    private void dob_purchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dob_purchaseActionPerformed
     err_date.setText("");
     try{
     String date = null;
     java.util.Date date1=dob_purchase.getDate();
     DateFormat formate1=new SimpleDateFormat("yyyy-MM-dd");
     date=formate1.format(date1);
     DateTimeFormatter f = DateTimeFormatter.ofPattern( "uuuu-MM-dd" ) ;
     LocalDate limit = LocalDate.parse( date , f ) ;
     ZoneId z = ZoneId.systemDefault() ;
     LocalDate today = LocalDate.now( z ) ;
     boolean isAfterLimit = today.isAfter(limit); 
    if(isAfterLimit==true)
    { 
        
    }
   
    else
    {
    JOptionPane.showMessageDialog(null, "Please enter a valid date");
    dob_purchase.setDate(null);
    }
    }
    catch(Exception e)
    {
    JOptionPane.showMessageDialog(null, "Error");
    }
    
    }//GEN-LAST:event_dob_purchaseActionPerformed

    private void txt_registrationKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_registrationKeyReleased
      err_no.setText("");
     
    }//GEN-LAST:event_txt_registrationKeyReleased

    private void txt_capacityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_capacityKeyReleased
      err_cap.setText("");
     
  
    }//GEN-LAST:event_txt_capacityKeyReleased

    private void cmb_modelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_modelActionPerformed
      err_model.setText("");    
       
    }//GEN-LAST:event_cmb_modelActionPerformed

    private void cmb_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_statusActionPerformed
       err_status.setText("");
     
    }//GEN-LAST:event_cmb_statusActionPerformed

    private void txt_priceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_priceKeyReleased
      err_price.setText(""); 
       
    }//GEN-LAST:event_txt_priceKeyReleased

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
         err_list.setText("");
    }//GEN-LAST:event_txt_searchKeyReleased

    private void txt_priceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_priceKeyTyped
       char c=evt.getKeyChar();
       if(Character.isLetter(c))
       {
           txt_price.setEditable(false);
       }
       else
       {
           txt_price.setEditable(true);
       }
    }//GEN-LAST:event_txt_priceKeyTyped

    private void txt_capacityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_capacityKeyTyped
        char c=evt.getKeyChar();
       if(Character.isLetter(c))
       {
           txt_capacity.setEditable(false);
       }
       else
       {
           txt_capacity.setEditable(true);
       }
    }//GEN-LAST:event_txt_capacityKeyTyped

    private void txt_capacityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_capacityFocusGained
       if(txt_capacity.getText().equals("In cubic feets"))
       {
           txt_capacity.setText("");
           txt_capacity.setForeground(Color.BLACK);
       }
    }//GEN-LAST:event_txt_capacityFocusGained

    private void txt_capacityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_capacityFocusLost
        if(txt_capacity.getText().equals(""))
       {
           txt_capacity.setText("In cubic feets");
           txt_capacity.setForeground(new Color(153,153,153));
       }
    }//GEN-LAST:event_txt_capacityFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageContainers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageContainers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageContainers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageContainers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageContainers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_search;
    private javax.swing.JComboBox<String> cmb_model;
    private javax.swing.JComboBox<String> cmb_status;
    private javax.swing.JTable container_tbl;
    private org.jdesktop.swingx.JXDatePicker dob_purchase;
    private javax.swing.JLabel err_cap;
    private javax.swing.JLabel err_date;
    private javax.swing.JLabel err_list;
    private javax.swing.JLabel err_model;
    private javax.swing.JLabel err_no;
    private javax.swing.JLabel err_price;
    private javax.swing.JLabel err_status;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_capacity;
    private javax.swing.JTextField txt_price;
    private javax.swing.JTextField txt_registration;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
