
package View;

import Control.CDeployContainers;
import Control.CReturnContainers;
import Model.MyDbConnection;
import static View.ReturnContainers.Instance;
import java.awt.Color;
import java.sql.Connection;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import org.jdesktop.swingx.JXDatePicker;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
public class ReturnContainers extends javax.swing.JFrame {

    public static  ReturnContainers Instance;
    public JTable tb0;
    public JTable tb1;
    public JTextField id;
    public JTextField reg22;
    public JTextField name;
    public JXDatePicker returndate;
    public JTextField delay;
    public JTextField fin;
    public ReturnContainers() {
        initComponents();
        Instance=this;
        tb0=deploy_tbl;
        tb1=return_tbl;
        id=txt_id;
        reg22=txt_registration;
        name=txt_name;
        returndate=dob_returndate;
        delay=txt_delay;
        fin=txt_final;
    }
 int fee=0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_registration = new javax.swing.JTextField();
        generate_lbl = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_delay = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_final = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        dob_returndate = new org.jdesktop.swingx.JXDatePicker();
        jLabel15 = new javax.swing.JLabel();
        btn_return = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        return_tbl = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        deploy_tbl = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        btn_rreturn = new javax.swing.JButton();
        btn_deploy1 = new javax.swing.JButton();
        err_id = new javax.swing.JLabel();
        err_regi = new javax.swing.JLabel();
        err_name = new javax.swing.JLabel();
        err_date = new javax.swing.JLabel();
        err_penalty = new javax.swing.JLabel();
        err_price = new javax.swing.JLabel();
        btn_clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("<<Back");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(524, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 600));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Return Containers");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, -1, -1));

        txt_id.setBackground(new java.awt.Color(255, 255, 255));
        txt_id.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 198, -1));

        txt_registration.setBackground(new java.awt.Color(255, 255, 255));
        txt_registration.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(txt_registration, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 198, -1));

        generate_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        generate_lbl.setForeground(new java.awt.Color(0, 0, 0));
        generate_lbl.setText("Generate Penalty");
        generate_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generate_lblMouseClicked(evt);
            }
        });
        jPanel3.add(generate_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, -1, -1));

        txt_name.setBackground(new java.awt.Color(255, 255, 255));
        txt_name.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 198, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Customer Name");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        txt_delay.setBackground(new java.awt.Color(255, 255, 255));
        txt_delay.setForeground(new java.awt.Color(0, 0, 0));
        txt_delay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_delayKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_delayKeyTyped(evt);
            }
        });
        jPanel3.add(txt_delay, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 198, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Delay Penalty");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, -1, -1));

        txt_final.setBackground(new java.awt.Color(255, 255, 255));
        txt_final.setForeground(new java.awt.Color(0, 0, 0));
        txt_final.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_finalKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_finalKeyTyped(evt);
            }
        });
        jPanel3.add(txt_final, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 198, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Final Price");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, -1, -1));

        dob_returndate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dob_returndateActionPerformed(evt);
            }
        });
        jPanel3.add(dob_returndate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 200, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Return Date");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        btn_return.setBackground(new java.awt.Color(255, 255, 255));
        btn_return.setForeground(new java.awt.Color(0, 153, 204));
        btn_return.setText("Returrn");
        btn_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_returnActionPerformed(evt);
            }
        });
        jPanel3.add(btn_return, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, 80, 40));

        return_tbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        return_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Deploy ID", "Registration No", "Customer Name", "Return Date", "Delay Penalty", "Final Price"
            }
        ));
        return_tbl.setRowHeight(23);
        return_tbl.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                return_tblAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane3.setViewportView(return_tbl);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 620, 170));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Deploy Id");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Deploy Containers List");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, -1));

        deploy_tbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deploy_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Deploy ID", "Registration No", "Model", "Customer Name", "Deploy Date", "Return Date", "Price"
            }
        ));
        deploy_tbl.setRowHeight(23);
        deploy_tbl.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                deploy_tblAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        deploy_tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deploy_tblMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(deploy_tbl);

        jPanel3.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 620, 160));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Registration");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        btn_rreturn.setForeground(new java.awt.Color(0, 153, 204));
        btn_rreturn.setText("Generate Return Report");
        btn_rreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rreturnActionPerformed(evt);
            }
        });
        jPanel3.add(btn_rreturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 470, -1, -1));

        btn_deploy1.setForeground(new java.awt.Color(0, 153, 204));
        btn_deploy1.setText("Generate Deploy Report");
        btn_deploy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deploy1ActionPerformed(evt);
            }
        });
        jPanel3.add(btn_deploy1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 230, -1, -1));
        jPanel3.add(err_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 200, 20));
        jPanel3.add(err_regi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 190, 20));
        jPanel3.add(err_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 200, 20));
        jPanel3.add(err_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 200, 20));
        jPanel3.add(err_penalty, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 190, 20));
        jPanel3.add(err_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 200, 20));

        btn_clear.setForeground(new java.awt.Color(0, 153, 204));
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        jPanel3.add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 530, 70, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 998, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void generate_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generate_lblMouseClicked
        if(fee==0)
        {
            JOptionPane.showMessageDialog(null,"select container to return");
        }
        else
        {
            int fine=fee+Integer.valueOf(txt_delay.getText());
            txt_final.setText("Rs"+fine);
        }
    }//GEN-LAST:event_generate_lblMouseClicked

    private void deploy_tblAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_deploy_tblAncestorAdded
        CReturnContainers b=new CReturnContainers();
        b.displayDeploy1();
    }//GEN-LAST:event_deploy_tblAncestorAdded

    private void deploy_tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deploy_tblMouseClicked
        err_id.setText("");
        err_regi.setText("");
        err_name.setText("");
        CReturnContainers m=new CReturnContainers();
        m.bringData1();
        DefaultTableModel model=(DefaultTableModel) deploy_tbl.getModel();
        int MyIndex=deploy_tbl.getSelectedRow();
        fee=Integer.valueOf(model.getValueAt(MyIndex, 6).toString());
    }//GEN-LAST:event_deploy_tblMouseClicked

    private void btn_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_returnActionPerformed
        if(txt_id.getText().trim().isEmpty())
        {
            err_id.setText("Id cannot be empty");
            err_id.setForeground(Color.red);
        }
        if(txt_registration.getText().trim().isEmpty())
        {
            err_regi.setText("Registration no cannot be empty");
            err_regi.setForeground(Color.red);
        }
        if(txt_name.getText().trim().isEmpty())
        {
            err_name.setText("Name cannot be empty");
            err_name.setForeground(Color.red);
        }
        if(dob_returndate.getDate()==null)
        {
            err_date.setText("Date cannot be empty");
            err_date.setForeground(Color.red);
        }
        if(txt_delay.getText().trim().isEmpty())
        {
            err_penalty.setText("Delay penalty cannot be empty");
            err_penalty.setForeground(Color.red);
        }
        if(txt_final.getText().trim().isEmpty())
        {
            err_price.setText("Fianl price cannot be empty");
            err_price.setForeground(Color.red);
        }
        else
        {String id,regi,name,date,price;
        int penalty;
        id=txt_id.getText();
        regi=txt_registration.getText();
        name=txt_name.getText();
        Date date1=dob_returndate.getDate();
        DateFormat formate1=new SimpleDateFormat("yyy-MM-dd");
        date=formate1.format(date1);
        penalty=Integer.parseInt(txt_delay.getText());
        price=txt_final.getText();
        
        CReturnContainers w=new CReturnContainers();
        w.returnData1(id,regi,name,date,penalty,price);
        
        }
    }//GEN-LAST:event_btn_returnActionPerformed

    private void return_tblAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_return_tblAncestorAdded
       CReturnContainers l=new CReturnContainers();
       l.displayReturn1();
    }//GEN-LAST:event_return_tblAncestorAdded

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
       this.toBack();
        setVisible(false);
        DashBoard b=new DashBoard();
        b.setVisible(true);
        b.toFront();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void btn_deploy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deploy1ActionPerformed
    
try {
            Connection con1=MyDbConnection.getConnection();
            
            JasperDesign Jdesign =JRXmlLoader.load("D:\\NetBeans\\Container\\Container\\Hit\\src\\View\\Deploy.jrxml");
            String query="select * from deploycontainers";
            
            JRDesignQuery updateQuery=new JRDesignQuery();
            updateQuery.setText(query);
            
            Jdesign.setQuery(updateQuery);
            JasperReport jreport=JasperCompileManager.compileReport(Jdesign);
            JasperPrint jprint=JasperFillManager.fillReport(jreport,null,con1);
            JasperViewer.viewReport(jprint);
            // TODO add your handling code here:
        } catch (JRException ex) {
            Logger.getLogger(ReturnContainers.class.getName()).log(Level.SEVERE, null, ex);
        } 
      
    }//GEN-LAST:event_btn_deploy1ActionPerformed

    private void btn_rreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rreturnActionPerformed
     try {
            Connection con1=MyDbConnection.getConnection();
            
            JasperDesign Jdesign =JRXmlLoader.load("D:\\NetBeans\\Container\\Container\\Hit\\src\\View\\ReturnReport.jrxml");
            String query="select * from returncontainers";
            
            JRDesignQuery updateQuery=new JRDesignQuery();
            updateQuery.setText(query);
            
            Jdesign.setQuery(updateQuery);
            JasperReport jreport=JasperCompileManager.compileReport(Jdesign);
            JasperPrint jprint=JasperFillManager.fillReport(jreport,null,con1);
            JasperViewer.viewReport(jprint);
            // TODO add your handling code here:
        } catch (JRException ex) {
            Logger.getLogger(DeployContainers.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }//GEN-LAST:event_btn_rreturnActionPerformed

    private void dob_returndateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dob_returndateActionPerformed
       err_date.setText("");
    }//GEN-LAST:event_dob_returndateActionPerformed

    private void txt_delayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_delayKeyReleased
     err_penalty.setText("");
    }//GEN-LAST:event_txt_delayKeyReleased

    private void txt_finalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_finalKeyReleased
      err_price.setText("");
    }//GEN-LAST:event_txt_finalKeyReleased

    private void txt_delayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_delayKeyTyped
        char c=evt.getKeyChar();
       if(Character.isLetter(c))
       {
           txt_delay.setEditable(false);
       }
       else
       {
           txt_delay.setEditable(true);
       }
    }//GEN-LAST:event_txt_delayKeyTyped

    private void txt_finalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_finalKeyTyped
        char c=evt.getKeyChar();
       if(Character.isLetter(c))
       {
           txt_final.setEditable(false);
       }
       else
       {
           txt_final.setEditable(true);
       }
    }//GEN-LAST:event_txt_finalKeyTyped

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        txt_id.setText("");
        txt_registration.setText("");
        txt_name.setText("");
        dob_returndate.setDate(null);
        txt_delay.setText("");
        txt_final.setText("");
        err_penalty.setText("");
        err_date.setText("");
        err_regi.setText("");
        err_id.setText("");
        err_name.setText("");
        err_price.setText("");
    }//GEN-LAST:event_btn_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnContainers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnContainers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnContainers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnContainers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnContainers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_deploy1;
    private javax.swing.JButton btn_return;
    private javax.swing.JButton btn_rreturn;
    private javax.swing.JTable deploy_tbl;
    private org.jdesktop.swingx.JXDatePicker dob_returndate;
    private javax.swing.JLabel err_date;
    private javax.swing.JLabel err_id;
    private javax.swing.JLabel err_name;
    private javax.swing.JLabel err_penalty;
    private javax.swing.JLabel err_price;
    private javax.swing.JLabel err_regi;
    private javax.swing.JLabel generate_lbl;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable return_tbl;
    private javax.swing.JTextField txt_delay;
    private javax.swing.JTextField txt_final;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_registration;
    // End of variables declaration//GEN-END:variables
}
